Repository namhyung/uftrace, pull requests merged in 2019-10, with the labels that each got.

#916 mcount: Fix a typo in comment
  arch/x86_64/dynamic.S
Labels: contributon2019

#929 doc/ko: Translate man page of uftrace dump
  doc/ko/uftrace-dump.md
  doc/uftrace-dump.md
Labels: contributon2019

#942 plthook: Remove dead code in find_got
  libmcount/plthook.c
Labels: contributon2019

#917 doc: Add Korean language translation for recv
  doc/ko/uftrace-recv.md
Labels: contributon2019

#946 info: Fix stack buffer overflow when reading cmdline
  cmds/info.c
Labels: contributon2019

#937 fstack: fix heap buffer overflow in read_task_arg
  utils/fstack.c
Labels: contributon2019

#975 uftrace: Fix typo and add comment for --chrome dump
  cmds/dump.c
  cmds/record.c
Labels: contributon2019

#966 uftrace: Fix fread() error handling
  cmds/info.c
  utils/symbol.c
Labels: contributon2019

#971 uftrace: Fix white space
  utils/data-file.c
  utils/debug.c
  utils/filter.c
  utils/fstack.h
  utils/kernel.c
  utils/perf.h
Labels: contributon2019

#982 live: Fix a memory leak in live replay
  utils/fstack.c
Labels: contributon2019

#987 uftrace: Fix fread() error handling
  cmds/info.c
  utils/symbol.c
Labels: contributon2019, critical

#967 android: Fix some of compile warnings and errors in android bionic
  cmds/record.c
  cmds/recv.c
  utils/compiler.h
  utils/utils.h
Labels: contributon2019

#974 live: Use current directory when /tmp is failed
  cmds/live.c
Labels: contributon2019

#922 record: Modify MCOUNT_MSG in record.c
  cmds/record.c
Labels: contributon2019

#924 doc/ko/uftrace.md: Korean translation
  doc/ko/uftrace.md
Labels: contributon2019

#866 script: Add luajit scripting support
  Makefile
  check-deps/Makefile
  check-deps/Makefile.check
  check-deps/__have_libluajit.c
  configure
  libmcount/mcount.c
  misc/install-deps.sh
  misc/version.sh
  scripts/count.lua
  scripts/dump.lua
  scripts/info.lua
  scripts/replay.lua
  scripts/simple.lua
  scripts/strings.lua
  scripts/trace-memcpy.lua
  tests/t234_script_luajit.py
  uftrace.c
  utils/script-luajit.c
  utils/script-luajit.h
  utils/script-python.c
  utils/script-python.h
  utils/script.c
  utils/script.h
Labels: contributon2019

#995 doc/ko:Translate uftrace-info.md to Korean
  doc/ko/uftrace-info.md
Labels: contributon2019, doc

#1006 misc: Fix tab size in install-deps.sh
  misc/install-deps.sh
Labels: contributon2019

#994 replay: Fix heap buffer overflow in get_argspec_string()
  cmds/replay.c
Labels: contributon2019

#998 info: Fix error when reading multiple cmdline
  cmds/info.c
Labels: contributon2019

#1000 dwarf: Fix white space
  utils/dwarf.c
Labels: contributon2019

#1007 uftrace: Fix memory leak in run_cmd
  uftrace.c
Labels: contributon2019

#992 doc/ko: Translate replay.md to Korean
  doc/ko/uftrace-replay.md
  doc/uftrace-replay.md
Labels: contributon2019, doc

#948 doc/ko: Translate man page of uftrace script
  doc/ko/uftrace-script.md
Labels: contributon2019, doc

#969 doc: Add Korean language translation for graph
  doc/ko/uftrace-graph.md
Labels: contributon2019, doc

#970 dump: Fix typo in comment
  cmds/dump.c
Labels: contributon2019

#990 uftrace: Fix typo in comment
  libmcount/mcount.c
  libmcount/plthook.c
  libmcount/record.c
  libmcount/wrap.c
Labels: contributon2019

#1009 dynamic: Fix a bug disallowing some functions to be patched
  arch/x86_64/mcount-insn.c
Labels: dynamic

#1002 uftrace: Fix .travis.yml to use install-dep.sh
  .travis.yml
  misc/install-deps.sh
Labels: contributon2019

#1015 doc: Update description of --tid option in related commands
  doc/uftrace-graph.md
  doc/uftrace-replay.md
  doc/uftrace-report.md
  doc/uftrace-script.md
  doc/uftrace-tui.md
Labels: doc

#953 doc: Fix typo and grammar in doc files
  doc/uftrace-graph.md
  doc/uftrace-live.md
  doc/uftrace-record.md
  doc/uftrace-report.md
Labels: contributon2019, doc
