Repository namhyung/uftrace, pull requests merged in 2022-08, with the labels that each got.

#1537 utils: Fix build problems when building with --without-libelf option
  utils/symbol-rawelf.h
Labels: ossca

#1523 test: Use both of gcc and clang by default
  tests/runtest.py
Labels: ossca

#1542 tests: Fix IndexError by checking report length
  tests/runtest.py
Labels: ossca

#1549 tests: Fix int conversion issue where zeros were discarded
  tests/t222_external_data.py
Labels: tests, ossca

#1550 utils: Fix the problem of handling numbers after the decimal point
  utils/utils.c
Labels: tests, ossca

#1554 tests: Fix random failures in diff tests
  tests/s-diff.c
  tests/t025_report_s_call.py
  tests/t158_report_diff_policy1.py
  tests/t159_report_diff_policy2.py
  tests/t160_report_diff_policy3.py
  tests/t177_report_diff_policy4.py
  tests/t240_report_diff_field2.py
  tests/t241_report_diff_field3.py
  tests/t242_report_diff_field4.py
  tests/t243_report_diff_field5.py
Labels: tests

#1557 tui: Add field "size" in report mode
  cmds/tui.c
  doc/ko/uftrace-tui.md
  doc/uftrace-tui.md
Labels: ossca

#1511 graph: Add the option to show function call graph as mermaid diagram
  cmds/dump.c
  doc/uftrace-dump.md
  tests/runtest.py
  tests/t272_dump_mermaid.py
  uftrace.c
  uftrace.h
  utils/graph.c
  utils/graph.h
Labels: ossca
