Repository namhyung/uftrace, pull requests merged in 2023-06, with the labels that each got.

#1725 python: Handle os._exit() properly
  python/trace-python.c
  python/uftrace.py
  tests/p011_libcall_nested.py
  tests/p012_os_exit.py
  tests/runtest.py
  tests/s-abc-exit.py
Labels: language support

#1715 doc: Describe agent usage
  doc/uftrace-live.md
  doc/uftrace-record.md
Labels: doc

#1732 doc: Add a python function tracing section in slide
  doc/uftrace.html
Labels: doc

#1733 doc: Add discord badge at the top of README.md
  README.md
Labels: doc

#1737 configure: fix error when building out of source
  configure
Labels: build
